### ISSUE TITLE
项目启动报错NullPointerException: targetAuthority

### ISSUE THREAD

**Issue by SlienceBao** [ChinaSilence/spring-boot-starter-grpc#10]
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'grpcClient' defined in class path resource [com/anoyi/grpc/config/GrpcAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.anoyi.grpc.GrpcClient]: Factory method 'grpcClient' threw exception; nested exception is java.lang.NullPointerException: targetAuthority

**Comment by AnoyiX** [comment]
详细描述下你的工程结构，和服务配置
