### ISSUE TITLE
使用sofa-hessian为默认的序列化方式，还能跨语言吗？

### ISSUE THREAD

**Issue by zhimiQi** [ChinaSilence/spring-boot-starter-grpc#15]
Hi，
我看了一下，你在新手手册里面写的是默认使用sofa-hessian的序列化方式，我去sofa-hessian的官网看了一下，没有提到可以跨语言使用，所以如果使用sofa-hessian的话，gRpc的在NodeJs，golang还有Python这边的跨语言还能用吗？
Thanks.

**Comment by AnoyiX** [comment]
目前支持 sofa-hessian   protobuf   json ，详见注解  @GrpcService

**Comment by zhimiQi** [comment]
> 目前支持 sofa-hessian protobuf json ，详见注解 @GrpcService
也就是如果要夸语言，最好改成protobuf和json是把，谢谢了
