### ISSUE TITLE
CommonServiceGrpc类

### ISSUE THREAD

**Issue by zhimiQi** [ChinaSilence/spring-boot-starter-grpc#17]
Hi，
CommonServiceGrpc 类没有，proto生成的只有GrpcService，请问是我命令有问题吗？
Thanks.

**Comment by zhimiQi** [comment]
。。。有人能帮忙看一下这个问题吗？

**Comment by AnoyiX** [comment]
https://github.com/ChinaSilence/spring-boot-starter-grpc/wiki

**Comment by zhimiQi** [comment]
> https://github.com/ChinaSilence/spring-boot-starter-grpc/wiki

不太懂，CommonServiceGrpc类没有，现在代码编译不过去呢...这个是代码引入的一个类，是CommonService的继承的一个基类，我仔细看了你的指导手册，它应该是有proto生成的。
代码如下：
`public class CommonService extends CommonServiceGrpc.CommonServiceImplBase {
`

**Comment by AnoyiX** [comment]
在 `spring-boot-starter-grpc/spring-boot-starter-grpc` 路径下执行 `mvn clean install`

**Comment by zhimiQi** [comment]
可以了..感谢您的指导...
