### ISSUE TITLE
跨语言调用问题

### ISSUE THREAD

**Issue by zhbitzwz** [ChinaSilence/spring-boot-starter-grpc#19]
请问怎么使用python/C++调用springboot-starter-grpc的接口，我试过使用你封装的python-grpc无法正常调用java的函数。

**Comment by AnoyiX** [comment]
应该是你没有写对



------------------ 原始邮件 ------------------
发件人: "ZWZ"<notifications@github.com>; 
发送时间: 2019年9月25日(星期三) 晚上8:16
收件人: "ChinaSilence/spring-boot-starter-grpc"<spring-boot-starter-grpc@noreply.github.com>; 
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: [ChinaSilence/spring-boot-starter-grpc] 跨语言调用问题 (#19)




请问怎么使用python/C++调用springboot-starter-grpc的接口，我试过使用你封装的python-grpc无法正常调用java的函数。
 
&mdash;

**Comment by zhbitzwz** [comment]
您好，请问能提供下python、java，c++互调的函数代码块参考吗，我这边可能函数名和参数类型对应不上？谢谢。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Anoyi"<notifications@github.com&gt;;
发送时间:&nbsp;2019年9月25日(星期三) 晚上8:49
收件人:&nbsp;"ChinaSilence/spring-boot-starter-grpc"<spring-boot-starter-grpc@noreply.github.com&gt;;
抄送:&nbsp;"ZWZ"<2998732468@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ChinaSilence/spring-boot-starter-grpc] 跨语言调用问题 (#19)



应该是你没有写对 
 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: "ZWZ"<notifications@github.com&gt;;  
 发送时间: 2019年9月25日(星期三) 晚上8:16 
 收件人: "ChinaSilence/spring-boot-starter-grpc"<spring-boot-starter-grpc@noreply.github.com&gt;;  
 抄送: "Subscribed"<subscribed@noreply.github.com&gt;;  
 主题: [ChinaSilence/spring-boot-starter-grpc] 跨语言调用问题 (#19) 
 
 
 
 
 请问怎么使用python/C++调用springboot-starter-grpc的接口，我试过使用你封装的python-grpc无法正常调用java的函数。 
   
 &amp;mdash;

**Comment by AnoyiX** [comment]
对应好包名、函数名、参数个数、顺序、类型，再加上网络，基本没什么问题的


------------------ 原始邮件 ------------------
发件人: "ZWZ"<notifications@github.com>;
发送时间: 2019年9月25日(星期三) 晚上10:43
收件人: "ChinaSilence/spring-boot-starter-grpc"<spring-boot-starter-grpc@noreply.github.com>;
抄送: "杨远东"<545544032@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [ChinaSilence/spring-boot-starter-grpc] 跨语言调用问题 (#19)



您好，请问能提供下python、java，c++互调的函数代码块参考吗，我这边可能函数名和参数类型对应不上？谢谢。 
 
 
 
 
 ------------------&nbsp;原始邮件&nbsp;------------------ 
 发件人:&nbsp;"Anoyi"<notifications@github.com&gt;; 
 发送时间:&nbsp;2019年9月25日(星期三) 晚上8:49 
 收件人:&nbsp;"ChinaSilence/spring-boot-starter-grpc"<spring-boot-starter-grpc@noreply.github.com&gt;; 
 抄送:&nbsp;"ZWZ"<2998732468@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 
 主题:&nbsp;Re: [ChinaSilence/spring-boot-starter-grpc] 跨语言调用问题 (#19) 
 
 
 
 应该是你没有写对  
   
   
   
  ------------------ 原始邮件 ------------------  
  发件人: "ZWZ"<notifications@github.com&gt;;   
  发送时间: 2019年9月25日(星期三) 晚上8:16  
  收件人: "ChinaSilence/spring-boot-starter-grpc"<spring-boot-starter-grpc@noreply.github.com&gt;;   
  抄送: "Subscribed"<subscribed@noreply.github.com&gt;;   
  主题: [ChinaSilence/spring-boot-starter-grpc] 跨语言调用问题 (#19)  
   
   
   
   
  请问怎么使用python/C++调用springboot-starter-grpc的接口，我试过使用你封装的python-grpc无法正常调用java的函数。  
     
  &amp;mdash;

**Comment by zhbitzwz** [comment]
python客户端的代码块,java服务端接口和项目中的一样，不知道这样调用的对不对：
`
from grpclib import *

@grpc_service(server='user')
def deleteById(id):
    pass
`
`
servers = [Server('user', '127.0.0.1', 6565)]
response = deleteById('1')
print(response)
`

**Comment by AnoyiX** [comment]
python 包和 java 包路径要对应

**Comment by zhbitzwz** [comment]
我对应上了python和java上的包路径，但是py客户端那边一直报错
`
    response = grpc_client.connect(server).handle(
AttributeError: 'NoneType' object has no attribute 'handle'
`
