### ISSUE TITLE
客户端的Service无法注入

### ISSUE THREAD

**Issue by wujincheng2333** [ChinaSilence/spring-boot-starter-grpc#20]
服务端启动正常，客户端公共接口无法注入，@Autowired注解报红

@RunWith(SpringRunner.class)
@SpringBootTest
public class GrpcClientApplicationTests {

    @Test
    public void contextLoads() {
    }

    @Autowired
    private CommonService commonService;

    @Test
    public void testRpc() throws Exception{
        System.out.println(this.commonService.say("123"));
    }
}

**Comment by AnoyiX** [comment]
commonService 是你自己定义的吗？可能会和系统的冲突，建议换个名字试试




------------------ 原始邮件 ------------------
发件人: "wujincheng2333"<notifications@github.com>; 
发送时间: 2019年9月28日(星期六) 中午1:37
收件人: "ChinaSilence/spring-boot-starte"<spring-boot-starter-grpc@noreply.github.com>; 
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: [ChinaSilence/spring-boot-starter-grpc] 客户端的Service无法注入 (#20)




服务端启动正常，客户端公共接口无法注入，@Autowired注解报红
 
@RunWith(SpringRunner.class)
 @SpringBootTest
 public class GrpcClientApplicationTests {
 @Test public void contextLoads() { } @Autowired private CommonService commonService; @Test public void testRpc() throws Exception{     System.out.println(this.commonService.say("123")); }  
}
 
&mdash;

**Comment by wujincheng2333** [comment]
换了，还是不行

服务端代码：
//公共接口
@GrpcService(server = "stringTest")
public interface StringTestService {
    public String say(String msg);
}
//实现类
@Service
public class StringTestServiceImpl implements StringTestService {
    @Override
    public String say(String msg) {
        System.out.println("----");
        return msg;
    }
}
//配置文件
server.port=8080
# properties 格式
spring.grpc.enable=true
spring.grpc.port=6565

客户端代码：
//公共接口
@GrpcService(server = "stringTest")
public interface StringTestService {
    public String say(String msg);
}
//配置文件
server.port=8081
spring.grpc.remote-servers[0].server=stringTest
spring.grpc.remote-servers[0].host=127.0.0.1
spring.grpc.remote-servers[0].port=6565
//测试类调用
@RunWith(SpringRunner.class)
@SpringBootTest
public class GrpcClientApplicationTests {



    @Test
    public void contextLoads() {
    }


    @Autowired
    private StringTestService stringTestService;


    @Test
    public void testRpc() throws Exception{
        System.out.println(this.stringTestService.say("123"));
    }
}


//报错信息
============================
CONDITIONS EVALUATION REPORT
============================


Positive matches:
-----------------

   CodecsAutoConfiguration matched:
      - @ConditionalOnClass found required class 'org.springframework.http.codec.CodecConfigurer' (OnClassCondition)

   CodecsAutoConfiguration.JacksonCodecConfiguration matched:
      - @ConditionalOnClass found required class 'com.fasterxml.jackson.databind.ObjectMapper' (OnClassCondition)

   CodecsAutoConfiguration.JacksonCodecConfiguration#jacksonCodecCustomizer matched:
      - @ConditionalOnBean (types: com.fasterxml.jackson.databind.ObjectMapper; SearchStrategy: all) found bean 'jacksonObjectMapper' (OnBeanCondition)

   DispatcherServletAutoConfiguration matched:
      - @ConditionalOnClass found required class 'org.springframework.web.servlet.DispatcherServlet' (OnClassCondition)
      - found 'session' scope (OnWebApplicationCondition)

   DispatcherServletAutoConfiguration.DispatcherServletConfiguration matched:
      - @ConditionalOnClass found required class 'javax.servlet.ServletRegistration' (OnClassCondition)
      - Default DispatcherServlet did not find dispatcher servlet beans (DispatcherServletAutoConfiguration.DefaultDispatcherServletCondition)

   DispatcherServletAutoConfiguration.DispatcherServletRegistrationConfiguration matched:
      - @ConditionalOnClass found required class 'javax.servlet.ServletRegistration' (OnClassCondition)
      - DispatcherServlet Registration did not find servlet registration bean (DispatcherServletAutoConfiguration.DispatcherServletRegistrationCondition)

   DispatcherServletAutoConfiguration.DispatcherServletRegistrationConfiguration#dispatcherServletRegistration matched:
      - @ConditionalOnBean (names: dispatcherServlet; types: org.springframework.web.servlet.DispatcherServlet; SearchStrategy: all) found bean 'dispatcherServlet' (OnBeanCondition)

   EmbeddedWebServerFactoryCustomizerAutoConfiguration matched:
      - @ConditionalOnWebApplication (required) found 'session' scope (OnWebApplicationCondition)

   EmbeddedWebServerFactoryCustomizerAutoConfiguration.TomcatWebServerFactoryCustomizerConfiguration matched:
      - @ConditionalOnClass found required classes 'org.apache.catalina.startup.Tomcat', 'org.apache.coyote.UpgradeProtocol' (OnClassCondition)

   ErrorMvcAutoConfiguration matched:
      - @ConditionalOnClass found required classes 'javax.servlet.Servlet', 'org.springframework.web.servlet.DispatcherServlet' (OnClassCondition)
      - found 'session' scope (OnWebApplicationCondition)

**Comment by AnoyiX** [comment]
我提供的 demo 能跑通吗



------------------ 原始邮件 ------------------
发件人: "wujincheng2333"<notifications@github.com>; 
发送时间: 2019年9月28日(星期六) 中午1:59
收件人: "ChinaSilence/spring-boot-starte"<spring-boot-starter-grpc@noreply.github.com>; 
抄送: "杨远东"<545544032@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [ChinaSilence/spring-boot-starter-grpc] 客户端的Service无法注入 (#20)




换了，还是不行
 
服务端代码：
 //公共接口
 @GrpcService(server = "stringTest")
 public interface StringTestService {
 public String say(String msg);
 }
 //实现类
 @service
 public class StringTestServiceImpl implements StringTestService {
 @override
 public String say(String msg) {
 System.out.println("----");
 return msg;
 }
 }
 //配置文件
 server.port=8080
 
properties 格式
 
spring.grpc.enable=true
 spring.grpc.port=6565
 
客户端代码：
 //公共接口
 @GrpcService(server = "stringTest")
 public interface StringTestService {
 public String say(String msg);
 }
 //配置文件
 server.port=8081
 spring.grpc.remote-servers[0].server=stringTest
 spring.grpc.remote-servers[0].host=127.0.0.1
 spring.grpc.remote-servers[0].port=6565
 //测试类调用
 @RunWith(SpringRunner.class)
 @SpringBootTest
 public class GrpcClientApplicationTests {
 @Test public void contextLoads() { } @Autowired private StringTestService stringTestService; @Test public void testRpc() throws Exception{     System.out.println(this.stringTestService.say("123")); }  
}
 
//报错信息
 
CONDITIONS EVALUATION REPORT
 
Positive matches:
 
CodecsAutoConfiguration matched:
 - @ConditionalOnClass found required class 'org.springframework.http.codec.CodecConfigurer' (OnClassCondition)
 
CodecsAutoConfiguration.JacksonCodecConfiguration matched:
 - @ConditionalOnClass found required class 'com.fasterxml.jackson.databind.ObjectMapper' (OnClassCondition)
 
CodecsAutoConfiguration.JacksonCodecConfiguration#jacksonCodecCustomizer matched:
 - @ConditionalOnBean (types: com.fasterxml.jackson.databind.ObjectMapper; SearchStrategy: all) found bean 'jacksonObjectMapper' (OnBeanCondition)
 
DispatcherServletAutoConfiguration matched:
 - @ConditionalOnClass found required class 'org.springframework.web.servlet.DispatcherServlet' (OnClassCondition)
 - found 'session' scope (OnWebApplicationCondition)
 
DispatcherServletAutoConfiguration.DispatcherServletConfiguration matched:
 - @ConditionalOnClass found required class 'javax.servlet.ServletRegistration' (OnClassCondition)
 - Default DispatcherServlet did not find dispatcher servlet beans (DispatcherServletAutoConfiguration.DefaultDispatcherServletCondition)
 
DispatcherServletAutoConfiguration.DispatcherServletRegistrationConfiguration matched:
 - @ConditionalOnClass found required class 'javax.servlet.ServletRegistration' (OnClassCondition)
 - DispatcherServlet Registration did not find servlet registration bean (DispatcherServletAutoConfiguration.DispatcherServletRegistrationCondition)
 
DispatcherServletAutoConfiguration.DispatcherServletRegistrationConfiguration#dispatcherServletRegistration matched:
 - @ConditionalOnBean (names: dispatcherServlet; types: org.springframework.web.servlet.DispatcherServlet; SearchStrategy: all) found bean 'dispatcherServlet' (OnBeanCondition)
 
EmbeddedWebServerFactoryCustomizerAutoConfiguration matched:
 - @ConditionalOnWebApplication (required) found 'session' scope (OnWebApplicationCondition)
 
EmbeddedWebServerFactoryCustomizerAutoConfiguration.TomcatWebServerFactoryCustomizerConfiguration matched:
 - @ConditionalOnClass found required classes 'org.apache.catalina.startup.Tomcat', 'org.apache.coyote.UpgradeProtocol' (OnClassCondition)
 
ErrorMvcAutoConfiguration matched:
 - @ConditionalOnClass found required classes 'javax.servlet.Servlet', 'org.springframework.web.servlet.DispatcherServlet' (OnClassCondition)
 - found 'session' scope (OnWebApplicationCondition)

**Comment by wujincheng2333** [comment]
可以
