### ISSUE TITLE
性能怎么样

### ISSUE THREAD

**Issue by wangliguang517** [ChinaSilence/spring-boot-starter-grpc#31]
请问压测的结果怎么样？
1，在多线程的情况下，速度，qps，和抗压能力
2，在请求、返回大数据时，速度，qps，和抗压能力
3，1、2累加后，速度，qps，和抗压能力怎么样？

因为我看底层封装，就是封装了一个grpc作为底层通讯，这样会不会在压力大的时候造成性能瓶颈呢？

**Comment by AnoyiX** [comment]
这些取决于你服务端的配置，这里只做了编码方面的封装，而且设计的初衷是应用于  Service Mesh，服务端多副本部署，就能更抗压

**Comment by wangliguang517** [comment]
grpc解决的是服务间的调用，我的意思是，这个服务间调用性能怎么样，有没有压测过，比如大参数，小参数，。。。

**Comment by wangliguang517** [comment]
grpc解决的是服务间的调用，
我的意思是，这个服务间调用性能怎么样，有没有压测过，比如：大参数，小参数，。。。高压力下grpc会不会成为瓶颈。
比如：这个grpc和http传输工具(如httpclient)间是否有压测比对

**Comment by AnoyiX** [comment]
这个测试比较容易做的，把底层 gRPC 的请求方式用 HttpClient 写一遍就能测了
