### ISSUE TITLE
服务端异常处理

### ISSUE THREAD

**Issue by xu982604405** [ChinaSilence/spring-boot-starter-grpc#5]
com.anoyi.grpc.service.CommonService 类的handle方法的异常处理逻辑，输出的异常有些问题
针对InvocationTargetException 异常，真实的异常应该在cause里面
如下实现
catch (NoSuchBeanDefinitionException | ClassNotFoundException  exception) {
			String message = exception.getClass().getName() + ": " + exception.getMessage();
			response.error(message, exception, exception.getStackTrace());
			log.error("接口未实现", exception);//记录服务端异常
		} catch (InvocationTargetException e) {
			String message = e.getCause().getClass().getName() + ": " + e.getCause().getMessage();
			response.error(message, e.getCause(), e.getCause().getStackTrace());
			log.error("接口出现异常", e.getCause());//记录服务端异常
		}

**Comment by AnoyiX** [comment]
thanks for your suggestion




------------------ 原始邮件 ------------------
发件人: "xu982604405"<notifications@github.com>;
发送时间: 2019年1月8日(星期二) 下午4:56
收件人: "ChinaSilence/spring-boot-starter-grpc"<spring-boot-starter-grpc@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: [ChinaSilence/spring-boot-starter-grpc] 服务端异常处理 (#5)




com.anoyi.grpc.service.CommonService 类的handle方法的异常处理逻辑，输出的异常有些问题
 针对InvocationTargetException 异常，真实的异常应该在cause里面
 如下实现
 catch (NoSuchBeanDefinitionException | ClassNotFoundException  exception) {
 String message = exception.getClass().getName() + ": " + exception.getMessage();
 response.error(message, exception, exception.getStackTrace());
 log.error("接口未实现", exception);//记录服务端异常
 } catch (InvocationTargetException e) {
 String message = e.getCause().getClass().getName() + ": " + e.getCause().getMessage();
 response.error(message, e.getCause(), e.getCause().getStackTrace());
 log.error("接口出现异常", e.getCause());//记录服务端异常
 }
