### ISSUE TITLE
使用gradle构建client或者server时出错

### ISSUE THREAD

**Issue by somePeopleFireAndWood** [ChinaSilence/spring-boot-starter-grpc#8]
在使用gradle构建client或者server时，会报“Error:(18, 43) java: 变量 userServiceByProtoStuff 未在默认构造器中初始化”这个错误，如果使用maven构建则正常运行。请问可能是什么原因导致的，应该怎么解决？

**Comment by somePeopleFireAndWood** [comment]
刚刚发现使用gradle build的jar包可以正常运行，但是如果直接在idea里运行代码则会报这个错。

**Comment by AnoyiX** [comment]
你的 idea 上安装了 lombok 插件吗？

**Comment by somePeopleFireAndWood** [comment]
安装了lomcok插件

**Comment by AnoyiX** [comment]
先 install  spring-boot-starter-grpc 这个模块， client 和  server 都依赖这个模块

**Comment by somePeopleFireAndWood** [comment]
已经install完了，所以用maven构建时才能正常运行，打成的jar包也可以正常运行。

**Comment by AnoyiX** [comment]
gradle 不熟，需要你自己解决了 😔

**Comment by somePeopleFireAndWood** [comment]
请问master分支和2.0.0分支有什么区别吗？

**Comment by AnoyiX** [comment]
2.0.0 分支已移除

**Comment by somePeopleFireAndWood** [comment]
问题已经解决了，不是gradle的问题，是idea的enable annotation processing没有勾选使用导致的。
